[build]
  # Combined command to ensure dependencies install before build starts
  command = "npm install && npm run build"
  
  # Next.js build output is automatically handled by the plugin, but explicitly setting this is often safer.
  # The actual publish directory will be a hidden Netlify folder managed by the plugin.
  publish = "next" 

[build.environment]
  # Force a modern Node version compatible with Next.js 14
  NODE_VERSION = "20"
  
# =======================================================
# CRITICAL: Activate the Next.js Plugin for App Router Support
# This is the most important part to fix the 404 error.
# =======================================================
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# The following section is for development on Netlify Dev (optional, but good practice)
[dev]
  framework = "next"
  publish = ".next"
  targetPort = 3000
